version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"
    target-branch: "dev"

  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    assignees:
      - "Ziedelth"
    reviewers:
      - "Ziedelth"
    target-branch: "dev"
