version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/dependencies/logger/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/dependencies/notifications/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/dependencies/url/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android/app/"
    schedule:
      interval: "weekly"