name: jais
description: A Flutter application by Ziedelth for mobile users

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  shimmer: ^2.0.0
  json_annotation: ^4.4.0
  http: ^0.13.4
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: 'assets/icon.jpg'
  android: true
  ios: true

flutter:
  uses-material-design: true
