name: jais
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+2.10

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get_storage: ^2.0.3
  shimmer: ^2.0.0
  json_annotation: ^3.0.1
  http: ^0.13.4
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
