name: jais
description: A Flutter application by Ziedelth for mobile members

publish_to: 'none'
version: 1.1.3+10

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  badges: ^2.0.3
  brotli: ^0.5.0
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.0.1
  in_app_review: ^2.0.4
  json_annotation: ^4.6.0
  logger:
    path: dependencies/logger
  notifications:
    path: dependencies/notifications
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url:
    path: dependencies/url
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons_maker: ^0.10.2
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.9
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.1

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - 'assets/icon.png'
