name: jais
description: A Flutter application by Ziedelth for mobile members

publish_to: 'none'
version: 1.1.0+7

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  brotli: ^0.5.0
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.2
  get_storage: ^2.0.3
  google_mobile_ads: ^1.2.0
  json_annotation: ^4.5.0
  logger:
    path: dependencies/logger
  notifications:
    path: dependencies/notifications
  package_info_plus: ^1.4.2
  provider: ^6.0.3
  shimmer: ^2.0.0
  url:
    path: dependencies/url
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons_maker: ^0.10.2
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter_icons:
  image_path: 'assets/icon.jpg'
  android: true
  ios: true
  web: true

flutter_native_splash:
  color: "#000000"
  image: assets/splash.png

flutter:
  uses-material-design: true

  assets:
    - 'assets/icon.jpg'
    - 'assets/splash.png'

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
