name: jais
description: A Flutter application by Ziedelth for mobile users

publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12

  flutter:
    sdk: flutter

  flutter_native_splash: ^2.1.5
  get_storage: ^2.0.3
  google_mobile_ads: ^1.2.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2

  flutter_test:
    sdk: flutter

  json_serializable: ^6.1.5
  lint: ^1.8.2
  test: ^1.19.5

flutter_icons:
  image_path: 'assets/icon.jpg'
  android: true
  ios: true

flutter_native_splash:
  color: "#000000"
  image: assets/splash.png

flutter:
  uses-material-design: true
