name: notifications
description: A new Flutter package project.
version: 1.0.0
homepage: https://ziedelth.fr
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  logger:
    path: ../logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
