name: Flutter CI
on:
  - push
jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --no-color --no-sound-null-safety

  build-aab:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AppBundle
        run: flutter build appbundle --no-color --no-sound-null-safety