name: Flutter CI
on:
  - push
jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --no-color --no-sound-null-safety

      - name: Upload Actifact
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: ./build/app/outputs/apk/release/app-release.apk

  build-aab:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AppBundle
        run: flutter build appbundle --no-color --no-sound-null-safety

      - name: Upload Actifact
        uses: actions/upload-artifact@v2
        with:
          name: AAB
          path: ./build/app/outputs/bundle/release/app-release.aab

  deploy:
    runs-on: ubuntu-latest

    needs:
      - build-apk
      - build-aab

    steps:
      - name: Download all workflow run actifacts
        uses: actions/download-artifact@v2

      - name: Commands
        run: |
          ls